#!/bin/bash

# blk
# red
# grn
# ylw
# blu
# pur
# cyn
# wht

rst='\e[0m'    # Text Reset
### - Regular
blk='\e[0;30m' # Black
red='\e[0;31m' # Red
grn='\e[0;32m' # Green
ylw='\e[0;33m' # Yellow
blu='\e[0;34m' # Blue
pur='\e[0;35m' # Purple
cyn='\e[0;36m' # Cyan
wht='\e[0;37m' # White
### - Bold
bldblk='\e[1;30m' # Black
bldred='\e[1;31m' # Red
bldgrn='\e[1;32m' # Green
bldylw='\e[1;33m' # Yellow
bldblu='\e[1;34m' # Blue
bldpur='\e[1;35m' # Purple
bldcyn='\e[1;36m' # Cyan
bldwht='\e[1;37m' # White
### - Underline
unkblk='\e[4;30m' # Black
undred='\e[4;31m' # Red
undgrn='\e[4;32m' # Green
undylw='\e[4;33m' # Yellow
undblu='\e[4;34m' # Blue
undpur='\e[4;35m' # Purple
undcyn='\e[4;36m' # Cyan
undwht='\e[4;37m' # White
### - Background
bakblk='\e[40m'   # Black
bakred='\e[41m'   # Red
bakgrn='\e[42m'   # Green
bakylw='\e[43m'   # Yellow
bakblu='\e[44m'   # Blue
bakpur='\e[45m'   # Purple
bakcyn='\e[46m'   # Cyan
bakwht='\e[47m'   # White

# printf "fg regular green\n"
# printf "${grn}hello world!${rst}\n"
# 
# printf "\e[5mmust be blinking text\e[0m\n"
# printf "\e[5m\e[1mmust be blinking and bold text\e[0m\n"
# printf "\e[2mmust be dim text\e[0m\n"
# printf "\e[7minversed text colors\e[0m\n"
# printf "\e[3msome italic text\e[0m\n"

# printf "some normal text\n"
# printf "\e[41msome text with red background\e[0m and normal text\n"
# printf "\e[1;41msome bold text with red background\e[0m\n"
# printf "\e[1;4;41msome bold and underlined text with red background\e[0m\n"
# printf "\e[1m\e[4;41msome bold and underlined text with red background\e[0m\n"
# printf "\e[32;41msome green text with red background\e[0m\n"

declare -A colors

colors[0]='\e[41;30m'
colors[1]='\e[41;32m'
colors[2]='\e[41;34m'
colors[3]='\e[41;36m'
colors[4]='\e[41;37m'
colors[5]='\e[42;30m'
colors[6]='\e[42;31m'
colors[7]='\e[42;33m'
colors[8]='\e[42;34m'
colors[9]='\e[42;35m'
colors[10]='\e[42;37m'
colors[11]='\e[43;30m'
colors[12]='\e[43;32m'
colors[13]='\e[43;34m'
colors[14]='\e[43;35m'
colors[15]='\e[43;36m'
colors[16]='\e[43;37m'
colors[17]='\e[44;31m'
colors[18]='\e[44;32m'
colors[19]='\e[44;33m'
colors[20]='\e[44;35m'
colors[21]='\e[44;36m'
colors[22]='\e[44;37m'
colors[23]='\e[45;30m'
colors[24]='\e[45;32m'
colors[25]='\e[45;34m'
colors[26]='\e[45;36m'
colors[27]='\e[45;37m'
colors[28]='\e[46;30m'
colors[29]='\e[46;31m'
colors[30]='\e[46;33m'
colors[31]='\e[46;34m'
colors[32]='\e[46;35m'
colors[33]='\e[46;37m'

# for i in {40..47}
# do
# 	for j in {30..37}
# 	do
# 		printf "\\\e[${i};${j}m: \e[${j};${i}msome different bg colors tried with different fg colors\e[0m\n"
# 	done
# done

for i in {1..20}
do
	# col="${colors[$((RANDOM%34))]}"
	printf "${colors[$((RANDOM%34))]}random color text\e[0m\n"
done
