#!/bin/bash

### colors
rst='\e[0m'    # Text Reset
### - Regular
red='\e[0;31m' # Red
grn='\e[0;32m' # Green

addition()
{
	a=$(( 20 + RANDOM % 100 ))	# 20-119
	b=$(( 20 + RANDOM % 100 ))	# 20-119
	answer=$((a + b))

	printf "\t$a + $b = "
	read user_answer

	# compare
	if [ $answer -eq $user_answer ]
	then
		echo -e "${grn}✔${rst}"
	else
		echo -e "${red}✘${rst} $answer"
	fi
}

subtraction()
{
	a=$(( RANDOM % 100 ))	# 0-99
	b=$(( RANDOM % 100 ))	# 0-99
	answer=$((a - b))

	printf "\t$a - $b = "
	read user_answer

	# compare
	if [ $answer -eq $user_answer ]
	then
		echo -e "${grn}✔${rst}"
	else
		echo -e "${red}✘${rst} $answer"
	fi
}

multiplication()
{
	a=$(( 10 + RANDOM % 100 ))	# 10-109
	b=$(( 2  + RANDOM % 10 ))	# 2-11
	answer=$((a * b))

	printf "\t$a * $b = "
	read user_answer

	# compare
	if [ $answer -eq $user_answer ]
	then
		echo -e "${grn}✔${rst}"
	else
		echo -e "${red}✘${rst} $answer"
	fi
}

division()
{
	a=$(( 10 + RANDOM % 6 ))	# 10-15
	b=$(( 5 + RANDOM % 5 ))		# 5-9
	c=$((a * b))

	printf "\t$c / $b = "
	read user_answer

	# compare
	if [ $a -eq $user_answer ]
	then
		echo -e "${grn}✔${rst}"
	else
		echo -e "${red}✘${rst} $a"
	fi
}

opt=$(( RANDOM % 4 ))

case $opt in
	0)
		addition
		;;
	1)
		subtraction
		;;
	2)
		multiplication
		;;
	3)
		division
		;;
esac

