#!/bin/bash

tmux rename-window "desk"
tmux split-window -t 0 -l 36
tmux split-window -t 0 -h -l 113
tmux split-window -t 2 -h -l 75
tmux split-window -t 3 -h -l 37
tmux split-window -t 2
tmux split-window -t 3
tmux split-window -t 4
tmux send-keys -t 0 'weather' Enter
tmux send-keys -t 2 'vrr unisued 18' Enter
tmux send-keys -t 3 'vrr uniost 18' Enter
tmux send-keys -t 4 'vrr bilks 18 15' Enter
tmux send-keys -t 5 'vrr werstener 18 5' Enter
tmux send-keys -t 6 'vrr suedpark 18 5' Enter
tmux send-keys -t 7 'vrr volks 18 15' Enter
# tmux split-window -t 1 -h -l 217
# tmux send-keys -t 1 'watch -t cat ~/.logs/learnsessions.log' Enter
tmux send-keys -t 1 'sudo pacman -Suy && yaourt -Suy --aur'
tmux select-pane -t 1
# tmux split-window -h -c /home/ildar/.alias/notes
# tmux send-keys 'notes.calendar' Enter
# tmux select-layout even-horizontal
# tmux split-window -v 
# tmux send-keys 'notes.tolearn' Enter
# tmux split-window -v -l 8
# tmux clock-mode 
# tmux split-window -h 'loop cal 1800' 
# 
# tmux select-pane -t 0
# tbahn
# 
# tmux select-pane -t 9
# tweather
# 
# tmux select-pane -t 7
# tmux send-keys "sudo pacman -Suy --ignore tmux && yaourt -Suy --aur" 
