#!/bin/bash

tmux send-keys 'while :;do (x=`tput op` y=`printf %76s` ;for i in {0..256}; do o=00Si; echo -e ${o:${#o}-3:3} `tput setaf $i; tput setab $i` ${y// /=}$x; done); done' Enter
# tmux split-window -h
# tmux send-keys 'while :;do (x=`tput op` y=`printf %76s` ;for i in {0..256}; do o=00Si; echo -e ${o:${#o}-3:3} `tput setaf $i; tput setab $i` ${y// /=}$x; done); done' Enter
# tmux split-window -h
# tmux send-keys 'while :;do (x=`tput op` y=`printf %76s` ;for i in {0..256}; do o=00Si; echo -e ${o:${#o}-3:3} `tput setaf $i; tput setab $i` ${y// /=}$x; done); done' Enter
# tmux select-layout even-horizontal
