#!/bin/bash

dir=/home/ildar/lcthw/devpkg

tmux break-pane
tmux rename-window "lcthw"
tmux send-keys -t 0 "cd $dir" Enter
tmux split-window -h -c $dir
tmux split-window -c /home/ildar/lcthw -t 0 -p 20
tmux split-window -c /home/ildar/lcthw -t 1
tmux send-keys -t 1 "clear" Enter
tmux send-keys -t 1 "ls ${!#} | entr -c make ${!#%.*}" Enter
tmux send-keys -t 2 "clear" Enter
tmux send-keys -t 2 "echo ${!#%.*} | entr -c ./${!#%.*}" Enter
tmux send-keys -t 3 "clear" Enter
tmux send-keys -t 3 "echo ${!#%.*} | entr -c valgrind --leak-check=full ./${!#%.*}" Enter
tmux select-pane -t 0
tmux send-keys "vim -p Makefile $*" Enter
tmux send-keys -t 0 ":tablast" Enter
