#!/bin/bash

if [ $# -eq 0 -o "$1" = "--help" -o "$1" = "-h" ]
then
	echo 'Usage: new'
	exit 0
fi

get_args()
{
	for i in $*
	do
		if [ "$1" = "-h" ]
		then
		echo 'Usage: new'
			exit 0
		fi
	done
}

get_args $*
