#!/bin/bash                                                                                                                    
orig_pane=$(tmux display-message -p '#P')                                          

tmux split-window -v                                                            
tmux split-window -v                                                            
tmux select-pane -t $orig_pane                                                  
tmux split-window -v                                                            
# tmux select-pane -t 0                                                         
                                                                                
tmux send-keys -t 0 "uzziel" Enter                                                                                
tmux send-keys -t 1 "uzziel" Enter                                                                                
tmux send-keys -t 2 "uzziel" Enter                                                                                
tmux send-keys -t 3 "uzziel" Enter                                                                                
                                                                                
tmux send-keys -t 0 "ssh phil-fak-1" Enter                                     
tmux send-keys -t 1 "ssh phil-fak-2" Enter                                     
tmux send-keys -t 2 "ssh phil-fak-3" Enter                                     
tmux send-keys -t 3 "ssh phil-fak-5" Enter                                     

tmux send-keys -t 0 "set -o vi" Enter                                           
tmux send-keys -t 1 "set -o vi" Enter                                           
tmux send-keys -t 2 "set -o vi" Enter                                           
tmux send-keys -t 3 "set -o vi" Enter                                           

tmux send-keys -t 0 "zypper list-patches" Enter                                     
tmux send-keys -t 1 "zypper list-patches" Enter                                     
tmux send-keys -t 2 "zypper list-patches" Enter                                     
tmux send-keys -t 3 "zypper list-patches" Enter                                     
                                                                                
tmux select-pane -t 3
