#!/bin/bash

orig_pane=$(tmux display-message -p '#P')

tmux split-window -v 
# tmux select-pane -t $orig_pane
tmux split-window -v 
# tmux select-pane -R
tmux select-pane -t $orig_pane
tmux split-window -v 
# tmux select-pane -t 0

tmux send-keys -t 0 "ssh root@uzziel-dev" Enter
tmux send-keys -t 1 "ssh root@uzziel-dev" Enter
tmux send-keys -t 2 "ssh root@uzziel-dev" Enter
tmux send-keys -t 3 "ssh root@uzziel-dev" Enter

tmux send-keys -t 0 "ssh gate-devlab" Enter
tmux send-keys -t 1 "ssh gate-devlab" Enter
tmux send-keys -t 2 "ssh gate-devlab" Enter
tmux send-keys -t 3 "ssh gate-devlab" Enter

tmux send-keys -t 1 "ssh puppetmaster1" Enter
tmux send-keys -t 2 "ssh puppetslave1" Enter
tmux send-keys -t 3 "ssh puppetslave2" Enter

tmux send-keys -t 0 "set -o vi" Enter
tmux send-keys -t 1 "set -o vi" Enter
tmux send-keys -t 2 "set -o vi" Enter
tmux send-keys -t 3 "set -o vi" Enter

tmux select-pane -t $orig_pane

