#!/bin/bash

tmux send-keys "uzziel" Enter
tmux send-keys "ssh cyrus-be5" Enter
tmux send-keys "set -o vi" Enter
tmux send-keys "vim /var/lib/cyrus-imapd/sieve/f/fatkullin/Open-Xchange.script" Enter
tmux send-keys "/)" Enter
tmux send-keys "i, header :contains \"\" \"\"" Escape
tmux send-keys "F,yt)f\"a"

# ssh $user_backend $sievec $oxpath/Open-Xchange.{script,bc}
