#!/bin/bash

max=100

declare -a ops
ops[0]="+"
ops[1]="-"
ops[2]="*"

opnum=$(( RANDOM % 3 ))

a=$(( RANDOM % $max ))
b=$(( RANDOM % ($max / 10) ))

c=$(( a ${ops[$opnum]} b ))

echo -n "$a ${ops[$opnum]} $b = "
read res
if [[ $c -eq $res ]]
then
	echo "right!"
else
	echo "wrong! the answer was $c"
fi
