#!/bin/bash

tmux split-window -v -l 7 "loop 'vrr uniost 5' 15"
tmux display-pane
tmux split-window -h -t 3 "loop 'vrr unisued 5' 15" 
# tmux split-window -h
# tmux send-keys "loop 'vrr unisued 5' 15" Enter 

# tmux select-pane -U
# sleep 3
# tmux split-window -v -l 8
# sleep 3
# # tmux send-keys "loop 'vrr suedpark 6' 15" Enter 
# tmux split-window -h
# sleep 3
# # tmux send-keys "loop 'vrr werstener 6' 15" Enter 
# 
# tmux select-pane -U
# sleep 3
# tmux split-window -v -l 10
# sleep 3
# # tmux send-keys "loop 'vrr volks 8 10' 15" Enter 
# tmux split-window -h
# sleep 3
# # tmux send-keys "loop 'vrr bilks 8 10' 15" Enter 
# 
# tmux select-pane -U
