#!/bin/bash

# wait for the dock state to change
sleep 0.5
DOCKED=$(cat /sys/devices/platform/dock.2/docked)
case "$DOCKED" in
	"0")
		#undocked event - lets remove all connected outputs apart from LVDS
		for output in `xrandr -d :0.0 --verbose | grep " connected" | grep -v LVDS | awk '{print $1}'`
		do
			xrandr -d :0.0 --output $output --off
		done
		;;
	"1")
		for output in `xrandr -d :0.0 --verbose | grep " connected" | awk '{print $1}'`
		do
			xrandr -d :0.0 --output $output --off
		done
		xrandr --output HDMI1 --mode 1920x1200
		xrandr --output VGA1 --mode 1280x1024 --right-of HDMI1 --rotate right
		xrandr --output LVDS1 --off
		;;
esac
date >> ~/.logs/dock.log
exit 0
