#!/bin/bash

# if no params omitted print short user information
if [ $# -eq 0 ]
then
	echo "Usage: `basename $0` stop [lines] [offset]"
	echo "Usage: `basename $0` help"
	exit 1
fi

# if there is no lines-param (precise: if length of second param is zero),
# then set lines to 10
if [ -z "$2" ]
then
	LINES=10
else
	LINES=$2
fi

# same with the offset param
if [ -z "$3" ] 
then
	OFFSET=0
else
	OFFSET=$3
fi

# simply prints the help dialogue
help_dialogue()
{
		printf \
"possible stops:
	derendorfs
	rather
	mooren
	oberbilk
	werstener
	hbf
	suedpark
	bilks
	volks
	unisuedost
	unisued
	uniost
	uninord

lines:
means the lines shown like on a display of a stop.
if no lines omitted, 10 lines are shown.

offset:
if you don't want to know when the next bus comes immediately,
but e.g in 15 minutes, so append 15 as a third parameter.
		
example:
	vrr unisuedost 5 10
shows 5 lines of the very next possibilities in 10 minutes to
get away from the stop \"UNI SÜDOST\", in a loop.\n"
}

# pipe wget output through grep, sed, tr and column to get desired output
# like that of a true bus-stop terminal
retrieve_and_show()
{
	echo $'\t'---== $MSG ==---
	wget -q --output-document=- $URL |\
		grep -e line -e dest -e time |\
		sed -e 's/<div class=\"line\"> //' -e 's/<div class=\"dest\"> //' -e 's/<div class=\"time\"> //' -e 's/ <\/div>//' |\
		tr '\n' '\t' |\
		sed -e 's/ min/ min\n/g' -e 's/sofort/sofort\n/g' |\
		sed -e 's/^[ \t]*//' |\
		column -c 5 -ts $'\t' | head -c -1
}

# build the url for desired stop with lines and offset param
build_url()
{
	case "$1" in
		derendorfs)
			URL="https://vrrf.finalrewind.org/Düsseldorf/derendorf.html?frontend=html&no_lines=$LINES&offset=$OFFSET"
			MSG="DERENDORF S" ;;
		rather)
			URL="https://vrrf.finalrewind.org/Düsseldorf/rather%20str.html?frontend=html&no_lines=10&offset=10"
			MSG="RATHER STRASSE" ;;
		mooren)
			URL="https://vrrf.finalrewind.org/Düsseldorf/Moorenstraße.html?frontend=html&no_lines=$LINES&offset=$OFFSET"
			MSG="MOORENSTRASSE" ;;
		oberbilk)
			URL="https://vrrf.finalrewind.org/Düsseldorf/Oberbilk.html?frontend=html&no_lines=$LINES&offset=$OFFSET"
			MSG="OBERBILK S" ;;
		werstener)
			URL="https://vrrf.finalrewind.org/Düsseldorf/werstener%20Dorfstraße.html?frontend=html&no_lines=$LINES&offset=$OFFSET"
			MSG="WERSTENER" ;;
		hbf)
			URL="https://vrrf.finalrewind.org/Düsseldorf/Hauptbahnhof.html?frontend=html&no_lines=$LINES&offset=$OFFSET"
			MSG="HBF" ;;
		suedpark)
			URL="https://vrrf.finalrewind.org/Düsseldorf/Südpark.html?frontend=html&no_lines=$LINES&offset=$OFFSET"
			MSG="SÜDPARK" ;;
		bilks)
			URL="https://vrrf.finalrewind.org/Düsseldorf/Bilk%20S.html?frontend=html&no_lines=$LINES&offset=$OFFSET"
			MSG="BILK S" ;;
		volks)
			URL="https://vrrf.finalrewind.org/Düsseldorf/Volksgarten.html?frontend=html&no_lines=$LINES&offset=$OFFSET"
			MSG="VOLKSGARTEN" ;;
		unisuedost)
			URL="https://vrrf.finalrewind.org/Düsseldorf/Universität%20Südost.html?frontend=html&no_lines=$LINES&offset=$OFFSET" 
			MSG="UNI SÜDOST" ;;
		unisued)
			URL="https://vrrf.finalrewind.org/Düsseldorf/uni%20süd.html?frontend=html&no_lines=$LINES&offset=$OFFSET" 
			MSG="UNI SÜD" ;;
		uniost)
			URL="https://vrrf.finalrewind.org/Düsseldorf/uni%20ost%20botanischer%20garten.html?frontend=html&no_lines=$LINES&offset=$OFFSET" 
			MSG="UNI OST" ;;
		uninord)
			URL="https://vrrf.finalrewind.org/Düsseldorf/uni%20nord%20christophstraße.html?frontend=html&no_lines=$LINES&offset=$OFFSET" 
			MSG="UNI NORD" ;;
		help)
			help_dialogue
			exit 0 ;;
		*)		echo Die Haltestelle kenne ich nicht 
			exit 1 ;;
	esac 
}

# main
build_url $*
# retrieve_and_show
while :; do clear; retrieve_and_show; sleep 10; done
